---
title: "Iterations and Listcols"
output: github_document
---

```{r setup}
library(tidyverse)
library(rvest)

set.seed(1)
```

## Lists

You can put anything into lists

```{r}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "Jeff")
vec_logical = c(TRUE, TRUE, TRUE, FALSE)
```

```{r}
l = list(
  vec_numeric = 5:8,
  mat         = matrix(1:8, 2, 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(1000)))
l

l$vec_numeric
l[[1]]
l[[1]][1:3]
```

Lists can be accessed using names/indices 

## `for` loops

```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

is.list(list_norms)
```

apply function to each element of the list 

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}

mean_and_sd(list_norms[[1]])
mean_and_sd(list_norms[[2]])
mean_and_sd(list_norms[[3]])
mean_and_sd(list_norms[[4]])
```

Let's use a for loop:

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```

## Let's try map!

```{r}
output = map(list_norms, mean_and_sd)
```

## Map variants

```{r}
output = map_dbl(list_norms, median, .id = "input")

output = map_dfr(list_norms, mean_and_sd, .id = "input")
```

## List columns

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )

listcol_df |> pull(name)
listcol_df |> pull(samp)
```

Let's try some operations

```{r}
mean_and_sd(pull(listcol_df, samp)[[1]])
```

Can i just map instead of pulling each one sep? 

```{r}
map(pull(listcol_df, samp), mean_and_sd)
```

can we add a list column? 

```{r}
listcol_df = 
  listcol_df |> 
  mutate(summary = map(samp, mean_and_sd))

listcol_df
```

